export const ORDER_REQUESTED_LOADED = "ORDER_REQUESTED_LOADED";
export const ORDER_REJECTED_LOADED = "ORDER_REJECTED_LOADED";
export const ORDER_CANCELLED_LOADED = "ORDER_CANCELLED_LOADED";
export const ORDER_INPROGRESS_LOADED = "ORDER_INPROGRESS_LOADED";
export const ORDER_COMPLETED_LOADED = "ORDER_COMPLETED_LOADED";